# -*- coding: utf-8 -*-
"""Dades del quadern tècnic imprimible: una entrada per sessió lectiva.

Font única per a `generar_quadern_tecnic.py`. Cada sessió porta el títol
CANÒNIC de la guia docent (capçalera «## SESSIÓ n (2 h) — …»; SA9 usa les
fases de la taula «Seqüència de sessions») — `tools/qa.py` comprova que no
es desincronitzin. Els camps `avui` i `vocab` estan curats a mà des de les
guies i fitxes, en llenguatge d'alumne.

La darrera sessió de cada trimestre és la prova pràctica (`"prova": True`).
"""

def _s(sa, s, titol, avui, vocab, prova=False):
    return {"sa": sa, "s": s, "titol": titol, "avui": avui, "vocab": vocab,
            "prova": prova}

SESSIONS = {
    1: [
        _s("SA1", 1, "Què és un robot?",
           "Descobrir robots amagats a casa · Classificar en entrada-procés-sortida · Conèixer el mètode de projecte",
           "sistema embegut · entrada · procés · sortida · sensor · actuador"),
        _s("SA1", 2, "Arquitectura i seguretat",
           "Reconèixer les parts de la placa Arduino · Distingir digital d'analògic · Muntar amb seguretat",
           "microcontrolador · pin digital · pin analògic (A0-A5) · PWM (~) · 5V/GND"),
        _s("SA1", 3, "El primer programa",
           "Predir i llegir el codi Blink · Fer parpellejar un LED · Modificar el temps i crear un repte",
           "setup() · loop() · pinMode · digitalWrite · delay() · PRIMM"),
        _s("SA2", 1, "Variables i la primera sortida",
           "Encendre un LED amb Arduino · Usar constants i variables · Mesurar tensions amb el multímetre",
           "const int · variable · resistència 220 Ω · ànode · multímetre"),
        _s("SA2", 2, "Estructures de control: el semàfor",
           "Programar un semàfor de 3 LED · Repetir seqüències amb bucles · Afegir una fase nocturna",
           "for · if · seqüència · delay() · millis()"),
        _s("SA2", 3, "PWM: intensitat i color",
           "Regular la intensitat d'un LED · Fer un efecte fade · Barrejar colors amb un LED RGB",
           "PWM · analogWrite (0-255) · map() · LED RGB · pins ~"),
        _s("SA2", 4, "Producte: panell de senyalització",
           "Integrar RGB, piezo i relé · Programar estats amb color i so · Defensar el teu panell",
           "LED RGB · piezo · relé · estat · funció"),
        _s("SA3", 1, "Entrades digitals i monitor sèrie",
           "Llegir un polsador · Comptar premudes al monitor sèrie · Fer un LED mode toggle",
           "INPUT_PULLUP · digitalRead · antirebot (debounce) · Serial Monitor · toggle"),
        _s("SA3", 2, "Entrades analògiques",
           "Llegir potenciòmetre i LDR (0-1023) · Reescalar amb map() · Fer un llum automàtic",
           "analogRead · conversió A/D · map() · divisor de tensió · llindar"),
        _s("SA3", 3, "Funcions + PRODUCTE: alarma/aparcament",
           "Mesurar distància amb ultrasons · Escriure una funció pròpia · Tancar el producte de la SA",
           "HC-SR04 · pulseIn · mesuraDistancia() · Serial Plotter · pseudocodi"),
        _s("SA3", 4, "PROVA PRÀCTICA T1 (individual)",
           "Muntar i programar tot sol la llum de seguretat intel·ligent · Documentar el procés",
           "sensor→actuador · llindar · funció · INPUT_PULLUP · quadern tècnic",
           prova=True),
    ],
    2: [
        _s("SA4", 1, "El servomotor",
           "Controlar l'angle exacte d'un servo (0-180°) · Moure'l amb un potenciòmetre",
           "Servo.h · attach() · write(angle) · map() · alimentació externa"),
        _s("SA4", 2, "Motor DC i pont H",
           "Fer girar un motor endavant i enrere · Regular-ne la velocitat amb seguretat",
           "pont H (L298N) · IN1/IN2 · ENA · PWM · massa comuna · driver"),
        _s("SA4", 3, "Del sensor al moviment",
           "Fer que el moviment respongui a un sensor · Frenar segons la distància",
           "ultrasons · map() · percepció→acció · llindar de seguretat · realimentació"),
        _s("SA4", 4, "Producte: barrera automàtica",
           "Muntar una barrera que s'obre sola amb el sensor · Documentar i defensar el projecte",
           "servo · ultrasons · LED indicador · pseudocodi · defensa"),
        _s("SA5", 1, "Primers passos amb MicroPython",
           "Escriure el primer programa en Python · Fer servir la matriu LED i els botons",
           "from microbit import * · display.scroll() · indentació · botons A/B"),
        _s("SA5", 2, "Sensors integrats",
           "Fer un comptapassos i un llum automàtic · Filtrar bé les lectures dels sensors",
           "acceleròmetre · read_light_level() · llindar · antirebot · sleep()"),
        _s("SA5", 3, "Ràdio i comparació de paradigmes",
           "Comunicar dues plaques sense cables · Comparar C++ i Python",
           "radio.on() · radio.config(group) · send() · receive() · taula comparativa"),
        _s("SA6", 1, "Què és un sistema de control?",
           "Distingir llaç obert de llaç tancat · Dibuixar el diagrama de blocs del sistema",
           "consigna · realimentació · error · actuador · llaç obert/tancat"),
        _s("SA6", 2, "Control tot/res i histèresi",
           "Fer un termòstat que no faci «clic-clic» · Entendre per què calen dos llindars",
           "control tot/res · histèresi · dos llindars · NTC · consigna"),
        _s("SA6", 3, "Màquines d'estats + tancament del producte",
           "Organitzar el comportament en estats i transicions · Programar sense bloquejar",
           "enum · switch · estats · transicions · millis()"),
        _s("SA6", 4, "PROVA PRÀCTICA T2 (individual)",
           "Demostrar tot sol el control amb histèresi · Fer la part de micro:bit en solitari",
           "histèresi · màquina d'estats · micro:bit · quadern consultable",
           prova=True),
    ],
    3: [
        _s("SA7", 1, "Moviment i cinemàtica diferencial",
           "Ajustar els pins del robot · Programar endavant, gir i aturada · Entendre per què gira",
           "cinemàtica diferencial · velocitat de roda · gir · calibratge"),
        _s("SA7", 2, "Trajectòries programades",
           "Fer recórrer un quadrat al robot · Calibrar el gir de 90° · Mesurar l'error i ajustar",
           "trajectòria · gir de 90° · control per temps · error de trajectòria"),
        _s("SA7", 3, "Evitar obstacles (comportament reactiu)",
           "Programar el robot amb ultrasons · Percebre, decidir i actuar · Millorar l'estratègia de gir",
           "ultrasons · llaç tancat · percepció-decisió-acció · màquina d'estats"),
        _s("SA7", 4, "Seguidor de línia + repte de pista",
           "Calibrar els sensors IR · Completar la pista de manera autònoma · Mesurar temps i iterar",
           "sensors IR · seguidor de línia · llindar · correcció proporcional · iteració"),
        _s("SA8", 1, "Telemetria: el robot que informa",
           "Enviar dades per ràdio · Rebre-les i registrar-les pel sèrie · Etiquetar dues magnituds",
           "telemetria · ràdio · group · port sèrie · llindar"),
        _s("SA8", 2, "IoT: arquitectura, aplicacions i riscos (auditoria d'un producte real)",
           "Dibuixar l'arquitectura del producte · Auditar dades i riscos · Defensar l'informe al peritatge",
           "IoT · dispositiu-xarxa-núvol-app · MQTT/WiFi · privacitat · RGPD · auditoria"),
        _s("SA8", 3, "Introducció a la IA: de les regles a l'aprenentatge",
           "Classificar gestos amb regles · Entrenar un model amb exemples · Reflexionar sobre el biaix",
           "regles · aprenentatge automàtic (ML) · classificador · entrenament · biaix"),
        _s("SA9", 1, "Projecte: idear",
           "Triar el repte i els requisits · Repartir rols d'equip · Fer l'esbós i el taulell",
           "repte · requisits mínims · esbós · planificació àgil · rols · kanban"),
        _s("SA9", 2, "Projecte: prototipar",
           "Muntar el prototip mínim viable · Escriure el primer codi partint de l'esquelet",
           "prototip mínim viable (MVP) · esquelet de codi · codi modular · integració"),
        _s("SA9", 3, "Projecte: provar i millorar",
           "Provar el sistema · Registrar els errors · Iterar la millora i avançar el dossier",
           "proves sistemàtiques · registre d'errors · iteració · code review · DEPURA"),
        _s("SA9", 4, "Projecte: comunicar (defensa)",
           "Tancar el dossier tècnic · Defensar el projecte oralment amb demostració · Coavaluar i reflexionar",
           "dossier tècnic · defensa oral · demostració · coavaluació · reflexió ètica"),
        _s("SA9", 5, "PROVA PRÀCTICA T3 (individual)",
           "Demostrar tot sol el robot a la pista (per torns) · Fer la part de micro:bit a la taula",
           "recorregut · obstacle · telemetria · estacions rotatives · quadern consultable",
           prova=True),
    ],
}

# Prova pràctica de cada trimestre (Avaluació/Prova_practica_Tn.md).
PROVES = {
    1: {"titol": "Llum de seguretat intel·ligent",
        "material": "Arduino UNO · protoboard · LDR + 10 kΩ · LED + 220 Ω · polsador · brunzidor · cables",
        "reflexio_final": False},
    2: {"titol": "Control climàtic + estació remota",
        "material": "Arduino UNO · ventilador/pont H (o LED PWM) · NTC o potenciòmetre · 2 micro:bit",
        "reflexio_final": False},
    3: {"titol": "Robot autònom + sistema connectat",
        "material": "Robot mòbil (Imagina 3dBot) · pista de proves · micro:bit",
        "reflexio_final": True},
}

# Situacions d'aprenentatge de cada trimestre (per a portada i índex).
SA_TRIMESTRE = {
    1: [("SA1", "Què és un robot?"), ("SA2", "Sortides digitals i PWM"),
        ("SA3", "Entrades i sensors")],
    2: [("SA4", "Moviment: servos, motors i ponts H"), ("SA5", "micro:bit i MicroPython"),
        ("SA6", "Sistemes de control")],
    3: [("SA7", "Robòtica mòbil"), ("SA8", "IoT i IA"),
        ("SA9", "Repte final integrador")],
}
